name: flutter_map_supercluster
description: Very fast Marker clustering for flutter_map. Supports efficient adding/removing of Markers.
version: 3.0.0+1

homepage: https://github.com/rorystephenson/flutter_map_supercluster

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  async: ^2.10.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_marker_popup: 
    git:
      url: https://github.com/Ltei/flutter_map_marker_popup
      ref: customBuilder
  latlong2: ^0.8.1
  provider: ^6.0.5
  supercluster: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
